// This file is generated by scripts/generate-blog-sources.mjs.
// Edit content/blog/*.md and run bun run blog:generate instead.

export const generatedBlogSources = [
  {
    "filename": "hello-from-the-machine.en.md",
    "slug": "hello-from-the-machine",
    "locale": "en",
    "frontmatter": {
      "tags": [
        "meta",
        "web"
      ],
      "draft": true
    },
    "source": "# Hello from the machine\n\nThis is a private starter post for checking the blog locally. Replace it with something real, add a `date`, and remove `draft: true` when it is ready to publish.\n\n## One file is enough\n\nThe filename supplies the slug and language. The first heading becomes the title, and the first paragraph becomes the summary shown in the archive.\n\n:::note\nCustom blocks stay readable in the Markdown source and become designed elements on the website.\n:::\n\n:::details{title=\"What gets generated automatically?\"}\nReading time, heading links, translation pairing, article metadata, RSS entries, and sitemap entries all come from this file.\n:::\n\n:::warning\nA draft without a publication date never enters the production blog, sitemap, or RSS feed.\n:::\n\n:::gallery\n![Homelab topology](/portfolio/personal/homelab/architecture.svg)\n![Virtual gamepad](/portfolio/personal/virtual-gamepad/controller.svg)\n:::\n\n## Code blocks know their language\n\nUse the normal language label after the opening fence. Highlighting happens while the page renders, so the browser only receives the finished markup.\n\n```ts\nconst post = \"content/blog/hello-from-the-machine.en.md\";\n```"
  },
  {
    "filename": "hello-from-the-machine.ru.md",
    "slug": "hello-from-the-machine",
    "locale": "ru",
    "frontmatter": {
      "tags": [
        "meta",
        "web"
      ],
      "draft": true
    },
    "source": "# Привет из машины\n\nЭто приватная стартовая запись для локальной проверки блога. Замени её настоящим текстом, добавь `date` и убери `draft: true`, когда запись будет готова к публикации.\n\n## Достаточно одного файла\n\nИмя файла задаёт slug и язык. Первый заголовок становится названием, а первый абзац — описанием в архиве.\n\n:::note\nКастомные блоки остаются читаемыми в Markdown и превращаются в оформленные элементы на сайте.\n:::\n\n:::details{title=\"Что создаётся автоматически?\"}\nВремя чтения, ссылки на разделы, связь переводов, метаданные статьи, RSS и sitemap формируются из этого файла.\n:::\n\n:::warning\nЧерновик без даты публикации никогда не попадёт в production-блог, sitemap или RSS.\n:::\n\n:::gallery\n![Схема домашней инфраструктуры](/portfolio/personal/homelab/architecture.svg)\n![Виртуальный геймпад](/portfolio/personal/virtual-gamepad/controller.svg)\n:::\n\n## Блоки кода знают свой язык\n\nИспользуйте обычное обозначение языка после открывающего fence. Подсветка происходит во время рендера страницы, а браузер получает уже готовую разметку.\n\n```ts\nconst post = \"content/blog/hello-from-the-machine.ru.md\";\n```"
  }
] as const;
